language: php
php:
  - 7.2
install:
  - composer install
before_script:
  - php -S 127.0.0.1:8888 -t tests/_data/docs >/dev/null
  - phantomjs --webdriver=4444 >/dev/null 2>&1 &
script:
  - vendor/bin/codecept run -d
